# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Страна',
                'verbose_name_plural': 'Страны',
            },
        ),
        migrations.CreateModel(
            name='SettlementType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид населённого пункта',
                'verbose_name_plural': 'Виды населённых пунктов',
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.country', verbose_name='Страна')),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.region', verbose_name='Регион')),
                ('settlement_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.settlementtype', verbose_name='Тип населённого пункта')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
            },
        ),
        migrations.CreateModel(
            name='Street',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('settlement', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.settlement', verbose_name='Населённый пункт')),
            ],
            options={
                'verbose_name': 'Улица',
                'verbose_name_plural': 'Улицы',
            },
        ),
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('postal_code', models.CharField(blank=True, max_length=10, verbose_name='Почтовый индекс')),
                ('house_number', models.CharField(max_length=10, verbose_name='Номер дома')),
                ('building', models.CharField(blank=True, max_length=10, verbose_name='Корпус')),
                ('structure', models.CharField(blank=True, max_length=10, verbose_name='Строение')),
                ('apartment', models.CharField(blank=True, max_length=10, verbose_name='Квартира')),
                ('street', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.street', verbose_name='Улица')),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.AddIndex(
            model_name='region',
            index=models.Index(fields=['country'], name='addresses_r_country_82b900_idx'),
        ),
        migrations.AddIndex(
            model_name='settlement',
            index=models.Index(fields=['region'], name='addresses_s_region__1c402b_idx'),
        ),
        migrations.AddIndex(
            model_name='street',
            index=models.Index(fields=['settlement'], name='addresses_s_settlem_b44e02_idx'),
        ),
        migrations.AddIndex(
            model_name='address',
            index=models.Index(fields=['street'], name='addresses_a_street__cf5e95_idx'),
        ),
    ]
