# Generated by Django 5.2.1 on 2025-05-10 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('employees', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='role',
        ),
        migrations.DeleteModel(
            name='Role',
        ),
    ]
