# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='contract',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='contractappendix',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddField(
            model_name='contractappendix',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='contractappendix',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='document',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='document',
            name='patient',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='contract',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='document',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.documentstatus', verbose_name='Статус'),
        ),
        migrations.AddField(
            model_name='document',
            name='document_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.documenttype', verbose_name='Тип документа'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.document', verbose_name='Документ'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='informedconsent',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='payment',
            name='contract',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contract', verbose_name='Договор'),
        ),
        migrations.AddIndex(
            model_name='contractappendix',
            index=models.Index(fields=['contract'], name='contracts_c_contrac_701b4a_idx'),
        ),
        migrations.AddIndex(
            model_name='contract',
            index=models.Index(fields=['patient'], name='contracts_c_patient_0c174b_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['patient'], name='contracts_d_patient_47bccd_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['employee'], name='contracts_d_employe_44b622_idx'),
        ),
        migrations.AddIndex(
            model_name='document',
            index=models.Index(fields=['document_type'], name='contracts_d_documen_08f055_idx'),
        ),
        migrations.AddIndex(
            model_name='informedconsent',
            index=models.Index(fields=['patient'], name='contracts_i_patient_68560c_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['contract'], name='contracts_p_contrac_145f99_idx'),
        ),
    ]
