# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dental', '0001_initial'),
        ('patients', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='prescription',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcard', verbose_name='Медицинская карта'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='medical_card_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcardinsert', verbose_name='Вкладыш медицинской карты'),
        ),
        migrations.AddField(
            model_name='prescription',
            name='nomenclature',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура'),
        ),
        migrations.AddField(
            model_name='toothformula',
            name='medical_card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcard', verbose_name='Медицинская карта'),
        ),
        migrations.AddField(
            model_name='toothformula',
            name='medical_card_insert',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcardinsert', verbose_name='Вкладыш медицинской карты'),
        ),
        migrations.AddField(
            model_name='tooth',
            name='tooth_formula',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dental.toothformula', verbose_name='Зубная формула'),
        ),
        migrations.AddField(
            model_name='tooth',
            name='position',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dental.toothposition', verbose_name='Позиция'),
        ),
        migrations.AddField(
            model_name='tooth',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dental.toothstatus', verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='prescription',
            index=models.Index(fields=['medical_card'], name='dental_pres_medical_0d2770_idx'),
        ),
        migrations.AddIndex(
            model_name='toothformula',
            index=models.Index(fields=['medical_card'], name='dental_toot_medical_ab4f50_idx'),
        ),
        migrations.AddIndex(
            model_name='tooth',
            index=models.Index(fields=['tooth_formula'], name='dental_toot_tooth_f_6108ce_idx'),
        ),
    ]
