# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('contracts', '0001_initial'),
        ('employees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NomenclatureType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид номенклатуры',
                'verbose_name_plural': 'Виды номенклатуры',
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('short_name', models.CharField(max_length=10, verbose_name='Краткое название')),
            ],
            options={
                'verbose_name': 'Единица измерения',
                'verbose_name_plural': 'Единицы измерения',
            },
        ),
        migrations.CreateModel(
            name='Nomenclature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('nomenclature_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclaturetype', verbose_name='Тип номенклатуры')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.unit', verbose_name='Единица измерения')),
            ],
            options={
                'verbose_name': 'Номенклатура',
                'verbose_name_plural': 'Номенклатура',
            },
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(verbose_name='Дата начала')),
                ('end_date', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='contracts.document', verbose_name='Документ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Прайс-лист',
                'verbose_name_plural': 'Прайс-листы',
            },
        ),
        migrations.CreateModel(
            name='PriceListItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='services.pricelist', verbose_name='Прайс-лист')),
            ],
            options={
                'verbose_name': 'Позиция прайс-листа',
                'verbose_name_plural': 'Позиции прайс-листа',
            },
        ),
        migrations.CreateModel(
            name='Manipulation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(verbose_name='Количество')),
                ('contract_appendix', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.contractappendix', verbose_name='Приложение к договору')),
                ('price_list_item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.pricelistitem', verbose_name='Позиция прайс-листа')),
            ],
            options={
                'verbose_name': 'Манипуляция',
                'verbose_name_plural': 'Манипуляции',
            },
        ),
        migrations.CreateModel(
            name='ServiceOnAppointment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('appointment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Запись на приём')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Услуга на приём',
                'verbose_name_plural': 'Услуги на приём',
            },
        ),
        migrations.AddIndex(
            model_name='pricelist',
            index=models.Index(fields=['start_date'], name='services_pr_start_d_557831_idx'),
        ),
        migrations.AddIndex(
            model_name='pricelistitem',
            index=models.Index(fields=['price_list'], name='services_pr_price_l_6d774f_idx'),
        ),
        migrations.AddIndex(
            model_name='manipulation',
            index=models.Index(fields=['contract_appendix'], name='services_ma_contrac_7a5389_idx'),
        ),
        migrations.AddIndex(
            model_name='serviceonappointment',
            index=models.Index(fields=['appointment'], name='services_se_appoint_c57207_idx'),
        ),
        migrations.AddIndex(
            model_name='nomenclature',
            index=models.Index(fields=['name'], name='services_no_name_b7e968_idx'),
        ),
    ]
