# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('appointments', '0001_initial'),
        ('employees', '0001_initial'),
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='cabinet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.cabinet', verbose_name='Кабинет'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.AddField(
            model_name='appointmentcancellation',
            name='appointment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.appointment', verbose_name='Запись на приём'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='appointment_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.appointmenttype', verbose_name='Тип приёма'),
        ),
        migrations.AddField(
            model_name='day',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.daystatus', verbose_name='Статус'),
        ),
        migrations.AddIndex(
            model_name='month',
            index=models.Index(fields=['name', 'year'], name='appointment_name_0c3b11_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='month',
            unique_together={('name', 'year')},
        ),
        migrations.AddField(
            model_name='day',
            name='month',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.month', verbose_name='Месяц'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='reminder_status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.reminderstatus', verbose_name='Статус напоминания'),
        ),
        migrations.AddField(
            model_name='schedule',
            name='day',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.day', verbose_name='День'),
        ),
        migrations.AddField(
            model_name='appointment',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='appointments.schedule', verbose_name='Расписание'),
        ),
        migrations.AddField(
            model_name='scheduleposition',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='scheduleposition',
            name='schedule',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointments.schedule', verbose_name='Расписание'),
        ),
        migrations.AddIndex(
            model_name='day',
            index=models.Index(fields=['month', 'number'], name='appointment_month_i_05c28b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='day',
            unique_together={('number', 'month')},
        ),
        migrations.AddIndex(
            model_name='schedule',
            index=models.Index(fields=['day'], name='appointment_day_id_8cf8cc_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['appointment_date'], name='appointment_appoint_5be6a4_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['employee'], name='appointment_employe_c6fb88_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['cabinet'], name='appointment_cabinet_cac350_idx'),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['schedule'], name='appointment_schedul_3da14c_idx'),
        ),
        migrations.AddIndex(
            model_name='scheduleposition',
            index=models.Index(fields=['employee'], name='appointment_employe_bfc1fb_idx'),
        ),
    ]
