# Generated by Django 5.2.1 on 2025-05-10 12:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('addresses', '0001_initial'),
        ('contracts', '0001_initial'),
        ('dental', '0001_initial'),
        ('employees', '0001_initial'),
        ('services', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Вид контактной информации',
                'verbose_name_plural': 'Виды контактной информации',
            },
        ),
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('М', 'Мужской'), ('Ж', 'Женский')], max_length=1, verbose_name='Пол')),
            ],
            options={
                'verbose_name': 'Пол',
                'verbose_name_plural': 'Полы',
            },
        ),
        migrations.CreateModel(
            name='PatientType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('service_conditions', models.TextField(blank=True, verbose_name='Условия обслуживания')),
            ],
            options={
                'verbose_name': 'Вид пациента',
                'verbose_name_plural': 'Виды пациентов',
            },
        ),
        migrations.CreateModel(
            name='MedicalCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mucosa_condition', models.TextField(blank=True, verbose_name='Состояние слизистой полости рта')),
                ('complaints', models.TextField(blank=True, verbose_name='Жалобы')),
                ('disease_history', models.TextField(blank=True, verbose_name='История болезней')),
                ('examination_data', models.TextField(blank=True, verbose_name='Данные осмотра')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.document', verbose_name='Документ')),
            ],
            options={
                'verbose_name': 'Медицинская карта',
                'verbose_name_plural': 'Медицинские карты',
            },
        ),
        migrations.CreateModel(
            name='MedicalCardInsert',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_complaints', models.TextField(blank=True, verbose_name='Жалобы на визите')),
                ('dental_history', models.TextField(blank=True, verbose_name='Стоматологический анамнез')),
                ('allergic_history', models.TextField(blank=True, verbose_name='Аллергологический анамнез')),
                ('visit_examination', models.TextField(blank=True, verbose_name='Данные осмотра на визите')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dental.diagnosis', verbose_name='Диагноз')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcard', verbose_name='Медицинская карта')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура')),
            ],
            options={
                'verbose_name': 'Вкладыш к медицинской карте',
                'verbose_name_plural': 'Вкладыши к медицинским картам',
            },
        ),
        migrations.CreateModel(
            name='Disease',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('diagnosis', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='dental.diagnosis', verbose_name='Диагноз')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcard', verbose_name='Медицинская карта')),
                ('medical_card_insert', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcardinsert', verbose_name='Вкладыш медицинской карты')),
            ],
            options={
                'verbose_name': 'Заболевание',
                'verbose_name_plural': 'Заболевания',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_name', models.CharField(max_length=100, verbose_name='Фамилия')),
                ('first_name', models.CharField(max_length=100, verbose_name='Имя')),
                ('middle_name', models.CharField(blank=True, max_length=100, verbose_name='Отчество')),
                ('birth_date', models.DateField(verbose_name='Дата рождения')),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='addresses.address', verbose_name='Адрес')),
                ('gender', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.gender', verbose_name='Пол')),
                ('patient_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.patienttype', verbose_name='Тип пациента')),
            ],
            options={
                'verbose_name': 'Пациент',
                'verbose_name_plural': 'Пациенты',
            },
        ),
        migrations.AddField(
            model_name='medicalcard',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент'),
        ),
        migrations.CreateModel(
            name='HealthQuestionnaire',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.document', verbose_name='Документ')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='employees.employee', verbose_name='Сотрудник')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Анкета здоровья',
                'verbose_name_plural': 'Анкеты здоровья',
            },
        ),
        migrations.CreateModel(
            name='ContactInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255, verbose_name='Значение')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='employees.employee', verbose_name='Сотрудник')),
                ('contact_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='patients.contacttype', verbose_name='Тип контакта')),
                ('patient', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='contacts', to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Контактная информация',
                'verbose_name_plural': 'Контактная информация',
            },
        ),
        migrations.CreateModel(
            name='PersonalDataConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('consent_date', models.DateField(verbose_name='Дата согласия')),
                ('expiry_date', models.DateField(blank=True, null=True, verbose_name='Дата истечения')),
                ('document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contracts.document', verbose_name='Документ')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient', verbose_name='Пациент')),
            ],
            options={
                'verbose_name': 'Согласие на обработку данных',
                'verbose_name_plural': 'Согласия на обработку данных',
            },
        ),
        migrations.CreateModel(
            name='Intolerance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomenclature', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='services.nomenclature', verbose_name='Номенклатура')),
                ('medical_card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.medicalcard', verbose_name='Медицинская карта')),
            ],
            options={
                'verbose_name': 'Непереносимое лекарство',
                'verbose_name_plural': 'Непереносимые лекарства',
                'indexes': [models.Index(fields=['medical_card'], name='patients_in_medical_80fdfc_idx')],
            },
        ),
        migrations.AddIndex(
            model_name='medicalcardinsert',
            index=models.Index(fields=['medical_card'], name='patients_me_medical_72b81a_idx'),
        ),
        migrations.AddIndex(
            model_name='disease',
            index=models.Index(fields=['medical_card'], name='patients_di_medical_51474f_idx'),
        ),
        migrations.AddIndex(
            model_name='medicalcard',
            index=models.Index(fields=['patient'], name='patients_me_patient_19a142_idx'),
        ),
        migrations.AddIndex(
            model_name='healthquestionnaire',
            index=models.Index(fields=['patient'], name='patients_he_patient_c13420_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['patient'], name='patients_co_patient_3becf2_idx'),
        ),
        migrations.AddIndex(
            model_name='contactinfo',
            index=models.Index(fields=['employee'], name='patients_co_employe_2dc6a2_idx'),
        ),
        migrations.AddIndex(
            model_name='patient',
            index=models.Index(fields=['last_name', 'first_name'], name='patients_pa_last_na_1b32a7_idx'),
        ),
        migrations.AddIndex(
            model_name='personaldataconsent',
            index=models.Index(fields=['patient'], name='patients_pe_patient_b403fe_idx'),
        ),
    ]
